apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ccc-realtime
  labels:
    cloud.googleapis.com/location: asia-south1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 250
      timeoutSeconds: 3600
      serviceAccountName: ccc-backend-sa@medicaps-production.iam.gserviceaccount.com
      containers:
        - image: gcr.io/medicaps-production/ccc-backend:v1.0.10
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "1000m"
              memory: "512Mi"
          env:
            - name: SERVICE_MODE
              value: "realtime"
            - name: ENVIRONMENT
              value: "production"
            - name: VERSION
              value: "1.0.10"
            - name: DB_POOL_SIZE
              value: "1"
            - name: DB_MAX_OVERFLOW
              value: "1"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: ccc-redis-host
                  key: latest
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ccc-redis-password
                  key: latest
