import {createFileRoute,Link,notFound} from "@tanstack/react-router";
import {useSuspenseQuery} from "@tanstack/react-query";
import {ArrowLeft,ArrowRight,CalendarCheck,Gift,ShieldCheck,Users} from "lucide-react";
import {Button} from "@/components/ui/button";
import {SectionHeader} from "@/organization/components/ui";
import {LifecycleBadge,Timeline,TwoStageIndicator} from "@/organization/components/ContestSystemUI";
import {contestSystemQueries} from "@/organization/data/contest-queries";
import {reviewState} from "@/organization/data/contest-system";
export const Route=createFileRoute("/portal/contests/$contestSlug/")({validateSearch:(s:Record<string,unknown>):{state?:ReturnType<typeof reviewState>|undefined}=>({state:s["state"]?reviewState(s["state"]):"default"}),loader:async({context,params})=>{const c=await context.queryClient.ensureQueryData(contestSystemQueries.contest(params.contestSlug));if(!c)throw notFound();return c},head:({loaderData})=>({meta:[{title:loaderData?`${loaderData.title} — CCC Medi-Caps`:"Contest unavailable"},{name:"description",content:loaderData?.summary??"Contest unavailable."},{property:"og:title",content:loaderData?.title??"Contest unavailable"},{property:"og:description",content:loaderData?.summary??"Contest unavailable."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:ContestDetail});
function ContestDetail(){const {contestSlug}=Route.useParams();const {state}=Route.useSearch();const {data:c}=useSuspenseQuery(contestSystemQueries.contest(contestSlug));if(!c)return null;const registered=state==="waiting"||state==="default"?c.registered:false;return <div className="page-wrap"><Link to="/portal/contests" search={{filter:"all",state:"default"}} className="back-link"><ArrowLeft/>All contests</Link><header className="contest-overview"><div><LifecycleBadge lifecycle={c.lifecycle}/><p className="kicker">{c.season}</p><h1>{c.title}</h1><p>{c.summary}</p><div className="button-row"><Button asChild><Link to="/portal/contests/$contestSlug/assessment" params={{contestSlug}} search={{state:registered?"waiting":"live"}} target="_blank" rel="noopener noreferrer">{registered?"View assessment status":"Register for contest"}<ArrowRight/></Link></Button><Button variant="outline" asChild><Link to="/portal/contests/$contestSlug/results" params={{contestSlug}} search={{state:"qualified",query:"",filter:"all",sort:"rank"}}>View Round 1 results</Link></Button></div></div><div className="format-emphasis"><p className="kicker">How this contest works</p><TwoStageIndicator stages={c.stages}/><p>Everyone begins online. Only the thirty highest verified Round 1 scores receive access to the on-campus final.</p></div></header>{registered&&<section className="registration-confirmed"><CalendarCheck/><div><strong>You’re registered for Round 1</strong><p>Your place is confirmed. Return when the assessment opens; we’ll notify you before the live window.</p></div><span>Opens 19 Sep · 18:00 IST</span></section>}<div className="content-grid contest-information"><section className="panel"><SectionHeader kicker="Four fixed moments" title="Contest timeline"/><Timeline contest={c}/></section><section className="panel"><SectionHeader kicker="Who can enter" title="Eligibility"/><ul className="check-list">{c.eligibility.map(x=><li key={x}><ShieldCheck/>{x}</li>)}</ul></section></div><section className="contest-lower"><div className="panel"><SectionHeader kicker="Both rounds" title="Rules and qualification"/><ol className="rule-list">{c.rules.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</li>)}</ol></div><div className="panel"><SectionHeader kicker="What is at stake" title="Prizes and recognition"/><ul className="prize-list">{c.prizes.map(x=><li key={x}><Gift/>{x}</li>)}</ul><div className="capacity-note"><Users/><span><strong>{c.registered_count}</strong> registered for Round 1</span></div></div></section></div>}
