import {createFileRoute,Link,useNavigate} from "@tanstack/react-router";
import {useSuspenseQuery} from "@tanstack/react-query";
import {ArrowRight,CalendarDays,Users} from "lucide-react";
import {Button} from "@/components/ui/button";
import {EmptyState,SectionHeader} from "@/organization/components/ui";
import {LifecycleBadge,TwoStageIndicator} from "@/organization/components/ContestSystemUI";
import {contestSystemQueries} from "@/organization/data/contest-queries";
import {reviewState} from "@/organization/data/contest-system";
const query=contestSystemQueries.contests();
export const Route=createFileRoute("/portal/contests/")({validateSearch:(s:Record<string,unknown>):{filter?:string|undefined;state?:ReturnType<typeof reviewState>|undefined}=>({filter:["all","upcoming","live","past"].includes(String(s["filter"]))?String(s["filter"]):"all",state:s["state"]?reviewState(s["state"]):"default"}),head:()=>({meta:[{title:"Two-Round Contests — CCC Medi-Caps"},{name:"description",content:"Register online, rank in the Top 30, and advance to CCC Medi-Caps live finals."},{property:"og:title",content:"Two-Round Contests — CCC Medi-Caps"},{property:"og:description",content:"Online assessments, Top 30 qualification, and live campus finals."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),loader:({context})=>context.queryClient.ensureQueryData(query),component:Contests});
function Contests(){const {data}=useSuspenseQuery(query);const {filter,state}=Route.useSearch();const navigate=useNavigate({from:Route.fullPath});const shown=state==="empty"?[]:data.filter(c=>filter==="all"||(filter==="upcoming"&&c.lifecycle==="registration_open")||(filter==="live"&&["assessment_live","results_pending","qualification_announced"].includes(c.lifecycle))||(filter==="past"&&c.lifecycle==="offline_complete"));return <div className="page-wrap"><header className="page-header"><div><p className="kicker">Online qualifier → campus final</p><h1>Two rounds. One final room.</h1><p>Start remotely in the open assessment. Finish on campus if your verified rank lands inside the Top 30.</p></div><div className="hub-stat"><strong>30</strong><span>FINALIST SEATS</span></div></header><div className="segmented">{["all","upcoming","live","past"].map(x=><Button key={x} variant={filter===x?"default":"ghost"} onClick={()=>void navigate({search:{filter:x,state}})}>{x}</Button>)}</div><section><SectionHeader kicker={`${shown.length} contests`} title="Contest calendar"/>{shown.length===0?<EmptyState title="No contests in this view" body="Try another filter. New two-round contests will appear here when announced."/>:shown.map(c=><article className="funnel-contest" key={c.slug}><div className="contest-card-main"><div className="contest-card-top"><LifecycleBadge lifecycle={c.lifecycle}/><span className="mono-tag">{c.season}</span></div><h2>{c.title}</h2><p>{c.summary}</p><TwoStageIndicator stages={c.stages} compact/><div className="event-facts"><span><CalendarDays/>Registration closes {new Date(c.registration_closes_at).toLocaleDateString("en-IN",{day:"numeric",month:"short"})}</span><span><Users/>{c.registered_count} registered</span></div></div><Link className="contest-card-open" to="/portal/contests/$contestSlug" params={{contestSlug:c.slug}} search={{state:"default"}} aria-label={`Open ${c.title}`}><ArrowRight/></Link></article>)}</section></div>}
