# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import fabric_pb2 as fabric__pb2
except ImportError:
    import fabric_pb2 as fabric__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fabric_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FabricControlPlaneStub:
    """==============================================================================
    Global Fabric Control Plane & Compute Node Protocol (gRPC / HTTP/2 + TLS)
    High-performance typed protocol for distributed nodes and cloud control plane
    ==============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/fabric.v1.FabricControlPlane/RegisterNode',
                request_serializer=fabric__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=fabric__pb2.RegisterNodeResponse.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/fabric.v1.FabricControlPlane/SendHeartbeat',
                request_serializer=fabric__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=fabric__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.DrainNode = channel.unary_unary(
                '/fabric.v1.FabricControlPlane/DrainNode',
                request_serializer=fabric__pb2.DrainNodeRequest.SerializeToString,
                response_deserializer=fabric__pb2.DrainNodeResponse.FromString,
                _registered_method=True)
        self.MarkReady = channel.unary_unary(
                '/fabric.v1.FabricControlPlane/MarkReady',
                request_serializer=fabric__pb2.ReadyNodeRequest.SerializeToString,
                response_deserializer=fabric__pb2.ReadyNodeResponse.FromString,
                _registered_method=True)
        self.ClaimJob = channel.unary_unary(
                '/fabric.v1.FabricControlPlane/ClaimJob',
                request_serializer=fabric__pb2.ClaimJobRequest.SerializeToString,
                response_deserializer=fabric__pb2.ClaimJobResponse.FromString,
                _registered_method=True)
        self.SubmitResult = channel.unary_unary(
                '/fabric.v1.FabricControlPlane/SubmitResult',
                request_serializer=fabric__pb2.SubmitResultRequest.SerializeToString,
                response_deserializer=fabric__pb2.SubmitResultResponse.FromString,
                _registered_method=True)
        self.ConnectFabric = channel.stream_stream(
                '/fabric.v1.FabricControlPlane/ConnectFabric',
                request_serializer=fabric__pb2.NodeTelemetry.SerializeToString,
                response_deserializer=fabric__pb2.FabricCommand.FromString,
                _registered_method=True)


class FabricControlPlaneServicer:
    """==============================================================================
    Global Fabric Control Plane & Compute Node Protocol (gRPC / HTTP/2 + TLS)
    High-performance typed protocol for distributed nodes and cloud control plane
    ==============================================================================

    """

    def RegisterNode(self, request, context):
        """1. Unary Operations for node lifecycle, heartbeat, and job dispatch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DrainNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectFabric(self, request_iterator, context):
        """2. Persistent Bidirectional Fabric Stream
        Multiplexes heartbeats, real-time job dispatch, capacity updates, and cancellations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FabricControlPlaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=fabric__pb2.RegisterNodeRequest.FromString,
                    response_serializer=fabric__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=fabric__pb2.HeartbeatRequest.FromString,
                    response_serializer=fabric__pb2.HeartbeatResponse.SerializeToString,
            ),
            'DrainNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DrainNode,
                    request_deserializer=fabric__pb2.DrainNodeRequest.FromString,
                    response_serializer=fabric__pb2.DrainNodeResponse.SerializeToString,
            ),
            'MarkReady': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkReady,
                    request_deserializer=fabric__pb2.ReadyNodeRequest.FromString,
                    response_serializer=fabric__pb2.ReadyNodeResponse.SerializeToString,
            ),
            'ClaimJob': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimJob,
                    request_deserializer=fabric__pb2.ClaimJobRequest.FromString,
                    response_serializer=fabric__pb2.ClaimJobResponse.SerializeToString,
            ),
            'SubmitResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitResult,
                    request_deserializer=fabric__pb2.SubmitResultRequest.FromString,
                    response_serializer=fabric__pb2.SubmitResultResponse.SerializeToString,
            ),
            'ConnectFabric': grpc.stream_stream_rpc_method_handler(
                    servicer.ConnectFabric,
                    request_deserializer=fabric__pb2.NodeTelemetry.FromString,
                    response_serializer=fabric__pb2.FabricCommand.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fabric.v1.FabricControlPlane', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fabric.v1.FabricControlPlane', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FabricControlPlane:
    """==============================================================================
    Global Fabric Control Plane & Compute Node Protocol (gRPC / HTTP/2 + TLS)
    High-performance typed protocol for distributed nodes and cloud control plane
    ==============================================================================

    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fabric.v1.FabricControlPlane/RegisterNode',
            fabric__pb2.RegisterNodeRequest.SerializeToString,
            fabric__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fabric.v1.FabricControlPlane/SendHeartbeat',
            fabric__pb2.HeartbeatRequest.SerializeToString,
            fabric__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DrainNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fabric.v1.FabricControlPlane/DrainNode',
            fabric__pb2.DrainNodeRequest.SerializeToString,
            fabric__pb2.DrainNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fabric.v1.FabricControlPlane/MarkReady',
            fabric__pb2.ReadyNodeRequest.SerializeToString,
            fabric__pb2.ReadyNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fabric.v1.FabricControlPlane/ClaimJob',
            fabric__pb2.ClaimJobRequest.SerializeToString,
            fabric__pb2.ClaimJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fabric.v1.FabricControlPlane/SubmitResult',
            fabric__pb2.SubmitResultRequest.SerializeToString,
            fabric__pb2.SubmitResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectFabric(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/fabric.v1.FabricControlPlane/ConnectFabric',
            fabric__pb2.NodeTelemetry.SerializeToString,
            fabric__pb2.FabricCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
