// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: fabric.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FabricControlPlane_RegisterNode_FullMethodName  = "/fabric.v1.FabricControlPlane/RegisterNode"
	FabricControlPlane_SendHeartbeat_FullMethodName = "/fabric.v1.FabricControlPlane/SendHeartbeat"
	FabricControlPlane_DrainNode_FullMethodName     = "/fabric.v1.FabricControlPlane/DrainNode"
	FabricControlPlane_MarkReady_FullMethodName     = "/fabric.v1.FabricControlPlane/MarkReady"
	FabricControlPlane_ClaimJob_FullMethodName      = "/fabric.v1.FabricControlPlane/ClaimJob"
	FabricControlPlane_SubmitResult_FullMethodName  = "/fabric.v1.FabricControlPlane/SubmitResult"
	FabricControlPlane_ConnectFabric_FullMethodName = "/fabric.v1.FabricControlPlane/ConnectFabric"
)

// FabricControlPlaneClient is the client API for FabricControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FabricControlPlaneClient interface {
	// 1. Unary Operations for node lifecycle, heartbeat, and job dispatch
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	DrainNode(ctx context.Context, in *DrainNodeRequest, opts ...grpc.CallOption) (*DrainNodeResponse, error)
	MarkReady(ctx context.Context, in *ReadyNodeRequest, opts ...grpc.CallOption) (*ReadyNodeResponse, error)
	ClaimJob(ctx context.Context, in *ClaimJobRequest, opts ...grpc.CallOption) (*ClaimJobResponse, error)
	SubmitResult(ctx context.Context, in *SubmitResultRequest, opts ...grpc.CallOption) (*SubmitResultResponse, error)
	// 2. Persistent Bidirectional Fabric Stream
	// Multiplexes heartbeats, real-time job dispatch, capacity updates, and cancellations
	ConnectFabric(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeTelemetry, FabricCommand], error)
}

type fabricControlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewFabricControlPlaneClient(cc grpc.ClientConnInterface) FabricControlPlaneClient {
	return &fabricControlPlaneClient{cc}
}

func (c *fabricControlPlaneClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, FabricControlPlane_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricControlPlaneClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, FabricControlPlane_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricControlPlaneClient) DrainNode(ctx context.Context, in *DrainNodeRequest, opts ...grpc.CallOption) (*DrainNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainNodeResponse)
	err := c.cc.Invoke(ctx, FabricControlPlane_DrainNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricControlPlaneClient) MarkReady(ctx context.Context, in *ReadyNodeRequest, opts ...grpc.CallOption) (*ReadyNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadyNodeResponse)
	err := c.cc.Invoke(ctx, FabricControlPlane_MarkReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricControlPlaneClient) ClaimJob(ctx context.Context, in *ClaimJobRequest, opts ...grpc.CallOption) (*ClaimJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimJobResponse)
	err := c.cc.Invoke(ctx, FabricControlPlane_ClaimJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricControlPlaneClient) SubmitResult(ctx context.Context, in *SubmitResultRequest, opts ...grpc.CallOption) (*SubmitResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResultResponse)
	err := c.cc.Invoke(ctx, FabricControlPlane_SubmitResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricControlPlaneClient) ConnectFabric(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeTelemetry, FabricCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FabricControlPlane_ServiceDesc.Streams[0], FabricControlPlane_ConnectFabric_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeTelemetry, FabricCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FabricControlPlane_ConnectFabricClient = grpc.BidiStreamingClient[NodeTelemetry, FabricCommand]

// FabricControlPlaneServer is the server API for FabricControlPlane service.
// All implementations must embed UnimplementedFabricControlPlaneServer
// for forward compatibility.
type FabricControlPlaneServer interface {
	// 1. Unary Operations for node lifecycle, heartbeat, and job dispatch
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	DrainNode(context.Context, *DrainNodeRequest) (*DrainNodeResponse, error)
	MarkReady(context.Context, *ReadyNodeRequest) (*ReadyNodeResponse, error)
	ClaimJob(context.Context, *ClaimJobRequest) (*ClaimJobResponse, error)
	SubmitResult(context.Context, *SubmitResultRequest) (*SubmitResultResponse, error)
	// 2. Persistent Bidirectional Fabric Stream
	// Multiplexes heartbeats, real-time job dispatch, capacity updates, and cancellations
	ConnectFabric(grpc.BidiStreamingServer[NodeTelemetry, FabricCommand]) error
	mustEmbedUnimplementedFabricControlPlaneServer()
}

// UnimplementedFabricControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFabricControlPlaneServer struct{}

func (UnimplementedFabricControlPlaneServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedFabricControlPlaneServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedFabricControlPlaneServer) DrainNode(context.Context, *DrainNodeRequest) (*DrainNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DrainNode not implemented")
}
func (UnimplementedFabricControlPlaneServer) MarkReady(context.Context, *ReadyNodeRequest) (*ReadyNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkReady not implemented")
}
func (UnimplementedFabricControlPlaneServer) ClaimJob(context.Context, *ClaimJobRequest) (*ClaimJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimJob not implemented")
}
func (UnimplementedFabricControlPlaneServer) SubmitResult(context.Context, *SubmitResultRequest) (*SubmitResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitResult not implemented")
}
func (UnimplementedFabricControlPlaneServer) ConnectFabric(grpc.BidiStreamingServer[NodeTelemetry, FabricCommand]) error {
	return status.Error(codes.Unimplemented, "method ConnectFabric not implemented")
}
func (UnimplementedFabricControlPlaneServer) mustEmbedUnimplementedFabricControlPlaneServer() {}
func (UnimplementedFabricControlPlaneServer) testEmbeddedByValue()                            {}

// UnsafeFabricControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FabricControlPlaneServer will
// result in compilation errors.
type UnsafeFabricControlPlaneServer interface {
	mustEmbedUnimplementedFabricControlPlaneServer()
}

func RegisterFabricControlPlaneServer(s grpc.ServiceRegistrar, srv FabricControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedFabricControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FabricControlPlane_ServiceDesc, srv)
}

func _FabricControlPlane_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricControlPlaneServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricControlPlane_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricControlPlaneServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricControlPlane_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricControlPlaneServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricControlPlane_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricControlPlaneServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricControlPlane_DrainNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricControlPlaneServer).DrainNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricControlPlane_DrainNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricControlPlaneServer).DrainNode(ctx, req.(*DrainNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricControlPlane_MarkReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadyNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricControlPlaneServer).MarkReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricControlPlane_MarkReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricControlPlaneServer).MarkReady(ctx, req.(*ReadyNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricControlPlane_ClaimJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricControlPlaneServer).ClaimJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricControlPlane_ClaimJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricControlPlaneServer).ClaimJob(ctx, req.(*ClaimJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricControlPlane_SubmitResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricControlPlaneServer).SubmitResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricControlPlane_SubmitResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricControlPlaneServer).SubmitResult(ctx, req.(*SubmitResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricControlPlane_ConnectFabric_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FabricControlPlaneServer).ConnectFabric(&grpc.GenericServerStream[NodeTelemetry, FabricCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FabricControlPlane_ConnectFabricServer = grpc.BidiStreamingServer[NodeTelemetry, FabricCommand]

// FabricControlPlane_ServiceDesc is the grpc.ServiceDesc for FabricControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FabricControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fabric.v1.FabricControlPlane",
	HandlerType: (*FabricControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _FabricControlPlane_RegisterNode_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _FabricControlPlane_SendHeartbeat_Handler,
		},
		{
			MethodName: "DrainNode",
			Handler:    _FabricControlPlane_DrainNode_Handler,
		},
		{
			MethodName: "MarkReady",
			Handler:    _FabricControlPlane_MarkReady_Handler,
		},
		{
			MethodName: "ClaimJob",
			Handler:    _FabricControlPlane_ClaimJob_Handler,
		},
		{
			MethodName: "SubmitResult",
			Handler:    _FabricControlPlane_SubmitResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConnectFabric",
			Handler:       _FabricControlPlane_ConnectFabric_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "fabric.proto",
}
