// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: fabric.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FabricCommand_CommandType int32

const (
	FabricCommand_NOOP         FabricCommand_CommandType = 0
	FabricCommand_DISPATCH_JOB FabricCommand_CommandType = 1
	FabricCommand_DRAIN        FabricCommand_CommandType = 2
	FabricCommand_RECONFIGURE  FabricCommand_CommandType = 3
)

// Enum value maps for FabricCommand_CommandType.
var (
	FabricCommand_CommandType_name = map[int32]string{
		0: "NOOP",
		1: "DISPATCH_JOB",
		2: "DRAIN",
		3: "RECONFIGURE",
	}
	FabricCommand_CommandType_value = map[string]int32{
		"NOOP":         0,
		"DISPATCH_JOB": 1,
		"DRAIN":        2,
		"RECONFIGURE":  3,
	}
)

func (x FabricCommand_CommandType) Enum() *FabricCommand_CommandType {
	p := new(FabricCommand_CommandType)
	*p = x
	return p
}

func (x FabricCommand_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FabricCommand_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_fabric_proto_enumTypes[0].Descriptor()
}

func (FabricCommand_CommandType) Type() protoreflect.EnumType {
	return &file_fabric_proto_enumTypes[0]
}

func (x FabricCommand_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FabricCommand_CommandType.Descriptor instead.
func (FabricCommand_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{18, 0}
}

type HardwareSpecs struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CpuCores           int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuThreads         int32                  `protobuf:"varint,2,opt,name=cpu_threads,json=cpuThreads,proto3" json:"cpu_threads,omitempty"`
	CpuModel           string                 `protobuf:"bytes,3,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	TotalMemoryMb      int64                  `protobuf:"varint,4,opt,name=total_memory_mb,json=totalMemoryMb,proto3" json:"total_memory_mb,omitempty"`
	AvailableMemoryMb  int64                  `protobuf:"varint,5,opt,name=available_memory_mb,json=availableMemoryMb,proto3" json:"available_memory_mb,omitempty"`
	Os                 string                 `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	Arch               string                 `protobuf:"bytes,7,opt,name=arch,proto3" json:"arch,omitempty"`
	DockerVersion      string                 `protobuf:"bytes,8,opt,name=docker_version,json=dockerVersion,proto3" json:"docker_version,omitempty"`
	DockerHealthy      bool                   `protobuf:"varint,9,opt,name=docker_healthy,json=dockerHealthy,proto3" json:"docker_healthy,omitempty"`
	SupportedLanguages []string               `protobuf:"bytes,10,rep,name=supported_languages,json=supportedLanguages,proto3" json:"supported_languages,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HardwareSpecs) Reset() {
	*x = HardwareSpecs{}
	mi := &file_fabric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareSpecs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareSpecs) ProtoMessage() {}

func (x *HardwareSpecs) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareSpecs.ProtoReflect.Descriptor instead.
func (*HardwareSpecs) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{0}
}

func (x *HardwareSpecs) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *HardwareSpecs) GetCpuThreads() int32 {
	if x != nil {
		return x.CpuThreads
	}
	return 0
}

func (x *HardwareSpecs) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *HardwareSpecs) GetTotalMemoryMb() int64 {
	if x != nil {
		return x.TotalMemoryMb
	}
	return 0
}

func (x *HardwareSpecs) GetAvailableMemoryMb() int64 {
	if x != nil {
		return x.AvailableMemoryMb
	}
	return 0
}

func (x *HardwareSpecs) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HardwareSpecs) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *HardwareSpecs) GetDockerVersion() string {
	if x != nil {
		return x.DockerVersion
	}
	return ""
}

func (x *HardwareSpecs) GetDockerHealthy() bool {
	if x != nil {
		return x.DockerHealthy
	}
	return false
}

func (x *HardwareSpecs) GetSupportedLanguages() []string {
	if x != nil {
		return x.SupportedLanguages
	}
	return nil
}

type DynamicCapacity struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JudgeSlots       int32                  `protobuf:"varint,1,opt,name=judge_slots,json=judgeSlots,proto3" json:"judge_slots,omitempty"`
	ApiWorkers       int32                  `protobuf:"varint,2,opt,name=api_workers,json=apiWorkers,proto3" json:"api_workers,omitempty"`
	SseConnections   int32                  `protobuf:"varint,3,opt,name=sse_connections,json=sseConnections,proto3" json:"sse_connections,omitempty"`
	ReservedMemoryMb int64                  `protobuf:"varint,4,opt,name=reserved_memory_mb,json=reservedMemoryMb,proto3" json:"reserved_memory_mb,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DynamicCapacity) Reset() {
	*x = DynamicCapacity{}
	mi := &file_fabric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicCapacity) ProtoMessage() {}

func (x *DynamicCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicCapacity.ProtoReflect.Descriptor instead.
func (*DynamicCapacity) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{1}
}

func (x *DynamicCapacity) GetJudgeSlots() int32 {
	if x != nil {
		return x.JudgeSlots
	}
	return 0
}

func (x *DynamicCapacity) GetApiWorkers() int32 {
	if x != nil {
		return x.ApiWorkers
	}
	return 0
}

func (x *DynamicCapacity) GetSseConnections() int32 {
	if x != nil {
		return x.SseConnections
	}
	return 0
}

func (x *DynamicCapacity) GetReservedMemoryMb() int64 {
	if x != nil {
		return x.ReservedMemoryMb
	}
	return 0
}

type RegisterNodeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname        string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	EnrollmentToken string                 `protobuf:"bytes,3,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"`
	AgentVersion    string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Hardware        *HardwareSpecs         `protobuf:"bytes,5,opt,name=hardware,proto3" json:"hardware,omitempty"`
	Capacity        *DynamicCapacity       `protobuf:"bytes,6,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_fabric_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterNodeRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *RegisterNodeRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterNodeRequest) GetHardware() *HardwareSpecs {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *RegisterNodeRequest) GetCapacity() *DynamicCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

type RegisterNodeResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	NodeId                   string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status                   string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "ready", "draining", etc.
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,3,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	AssignedQueue            string                 `protobuf:"bytes,4,opt,name=assigned_queue,json=assignedQueue,proto3" json:"assigned_queue,omitempty"`
	MaxConcurrency           int32                  `protobuf:"varint,5,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	Message                  string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_fabric_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterNodeResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *RegisterNodeResponse) GetAssignedQueue() string {
	if x != nil {
		return x.AssignedQueue
	}
	return ""
}

func (x *RegisterNodeResponse) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CpuUsagePct       float32                `protobuf:"fixed32,2,opt,name=cpu_usage_pct,json=cpuUsagePct,proto3" json:"cpu_usage_pct,omitempty"`
	MemoryUsagePct    float32                `protobuf:"fixed32,3,opt,name=memory_usage_pct,json=memoryUsagePct,proto3" json:"memory_usage_pct,omitempty"`
	AvailableMemoryMb int64                  `protobuf:"varint,4,opt,name=available_memory_mb,json=availableMemoryMb,proto3" json:"available_memory_mb,omitempty"`
	ActiveJobs        int32                  `protobuf:"varint,5,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	ActiveApiWorkers  int32                  `protobuf:"varint,6,opt,name=active_api_workers,json=activeApiWorkers,proto3" json:"active_api_workers,omitempty"`
	ActiveSseConns    int32                  `protobuf:"varint,7,opt,name=active_sse_conns,json=activeSseConns,proto3" json:"active_sse_conns,omitempty"`
	LatencyMs         float32                `protobuf:"fixed32,8,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	DockerHealthy     bool                   `protobuf:"varint,9,opt,name=docker_healthy,json=dockerHealthy,proto3" json:"docker_healthy,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_fabric_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetCpuUsagePct() float32 {
	if x != nil {
		return x.CpuUsagePct
	}
	return 0
}

func (x *HeartbeatRequest) GetMemoryUsagePct() float32 {
	if x != nil {
		return x.MemoryUsagePct
	}
	return 0
}

func (x *HeartbeatRequest) GetAvailableMemoryMb() int64 {
	if x != nil {
		return x.AvailableMemoryMb
	}
	return 0
}

func (x *HeartbeatRequest) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *HeartbeatRequest) GetActiveApiWorkers() int32 {
	if x != nil {
		return x.ActiveApiWorkers
	}
	return 0
}

func (x *HeartbeatRequest) GetActiveSseConns() int32 {
	if x != nil {
		return x.ActiveSseConns
	}
	return 0
}

func (x *HeartbeatRequest) GetLatencyMs() float32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *HeartbeatRequest) GetDockerHealthy() bool {
	if x != nil {
		return x.DockerHealthy
	}
	return false
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ShouldDrain   bool                   `protobuf:"varint,3,opt,name=should_drain,json=shouldDrain,proto3" json:"should_drain,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_fabric_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatResponse) GetShouldDrain() bool {
	if x != nil {
		return x.ShouldDrain
	}
	return false
}

func (x *HeartbeatResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DrainNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainNodeRequest) Reset() {
	*x = DrainNodeRequest{}
	mi := &file_fabric_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNodeRequest) ProtoMessage() {}

func (x *DrainNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNodeRequest.ProtoReflect.Descriptor instead.
func (*DrainNodeRequest) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{6}
}

func (x *DrainNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DrainNodeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DrainNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainNodeResponse) Reset() {
	*x = DrainNodeResponse{}
	mi := &file_fabric_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNodeResponse) ProtoMessage() {}

func (x *DrainNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNodeResponse.ProtoReflect.Descriptor instead.
func (*DrainNodeResponse) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{7}
}

func (x *DrainNodeResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *DrainNodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReadyNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyNodeRequest) Reset() {
	*x = ReadyNodeRequest{}
	mi := &file_fabric_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyNodeRequest) ProtoMessage() {}

func (x *ReadyNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyNodeRequest.ProtoReflect.Descriptor instead.
func (*ReadyNodeRequest) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{8}
}

func (x *ReadyNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ReadyNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyNodeResponse) Reset() {
	*x = ReadyNodeResponse{}
	mi := &file_fabric_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyNodeResponse) ProtoMessage() {}

func (x *ReadyNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyNodeResponse.ProtoReflect.Descriptor instead.
func (*ReadyNodeResponse) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{9}
}

func (x *ReadyNodeResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *ReadyNodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ClaimJobRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NodeId             string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TimeoutSeconds     float32                `protobuf:"fixed32,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	SupportedLanguages []string               `protobuf:"bytes,3,rep,name=supported_languages,json=supportedLanguages,proto3" json:"supported_languages,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClaimJobRequest) Reset() {
	*x = ClaimJobRequest{}
	mi := &file_fabric_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimJobRequest) ProtoMessage() {}

func (x *ClaimJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimJobRequest.ProtoReflect.Descriptor instead.
func (*ClaimJobRequest) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{10}
}

func (x *ClaimJobRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ClaimJobRequest) GetTimeoutSeconds() float32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ClaimJobRequest) GetSupportedLanguages() []string {
	if x != nil {
		return x.SupportedLanguages
	}
	return nil
}

type TestCase struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stdin          string                 `protobuf:"bytes,2,opt,name=stdin,proto3" json:"stdin,omitempty"`
	ExpectedOutput string                 `protobuf:"bytes,3,opt,name=expected_output,json=expectedOutput,proto3" json:"expected_output,omitempty"`
	Hidden         bool                   `protobuf:"varint,4,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Weight         float32                `protobuf:"fixed32,5,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestCase) Reset() {
	*x = TestCase{}
	mi := &file_fabric_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCase) ProtoMessage() {}

func (x *TestCase) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCase.ProtoReflect.Descriptor instead.
func (*TestCase) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{11}
}

func (x *TestCase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestCase) GetStdin() string {
	if x != nil {
		return x.Stdin
	}
	return ""
}

func (x *TestCase) GetExpectedOutput() string {
	if x != nil {
		return x.ExpectedOutput
	}
	return ""
}

func (x *TestCase) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *TestCase) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type JobSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	JobType       string                 `protobuf:"bytes,3,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Code          string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	TimeLimitMs   float32                `protobuf:"fixed32,6,opt,name=time_limit_ms,json=timeLimitMs,proto3" json:"time_limit_ms,omitempty"`
	MemoryLimitMb int64                  `protobuf:"varint,7,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"`
	Testcases     []*TestCase            `protobuf:"bytes,8,rep,name=testcases,proto3" json:"testcases,omitempty"`
	LeaseId       string                 `protobuf:"bytes,9,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Attempt       int32                  `protobuf:"varint,10,opt,name=attempt,proto3" json:"attempt,omitempty"`
	SubmissionId  string                 `protobuf:"bytes,11,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	ContestSlug   string                 `protobuf:"bytes,12,opt,name=contest_slug,json=contestSlug,proto3" json:"contest_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSpec) Reset() {
	*x = JobSpec{}
	mi := &file_fabric_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSpec) ProtoMessage() {}

func (x *JobSpec) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSpec.ProtoReflect.Descriptor instead.
func (*JobSpec) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{12}
}

func (x *JobSpec) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobSpec) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *JobSpec) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *JobSpec) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *JobSpec) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *JobSpec) GetTimeLimitMs() float32 {
	if x != nil {
		return x.TimeLimitMs
	}
	return 0
}

func (x *JobSpec) GetMemoryLimitMb() int64 {
	if x != nil {
		return x.MemoryLimitMb
	}
	return 0
}

func (x *JobSpec) GetTestcases() []*TestCase {
	if x != nil {
		return x.Testcases
	}
	return nil
}

func (x *JobSpec) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *JobSpec) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *JobSpec) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *JobSpec) GetContestSlug() string {
	if x != nil {
		return x.ContestSlug
	}
	return ""
}

type ClaimJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasJob        bool                   `protobuf:"varint,1,opt,name=has_job,json=hasJob,proto3" json:"has_job,omitempty"`
	Job           *JobSpec               `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimJobResponse) Reset() {
	*x = ClaimJobResponse{}
	mi := &file_fabric_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimJobResponse) ProtoMessage() {}

func (x *ClaimJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimJobResponse.ProtoReflect.Descriptor instead.
func (*ClaimJobResponse) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{13}
}

func (x *ClaimJobResponse) GetHasJob() bool {
	if x != nil {
		return x.HasJob
	}
	return false
}

func (x *ClaimJobResponse) GetJob() *JobSpec {
	if x != nil {
		return x.Job
	}
	return nil
}

type TestCaseResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Passed          bool                   `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	Verdict         string                 `protobuf:"bytes,3,opt,name=verdict,proto3" json:"verdict,omitempty"`
	ExecutionTimeMs float32                `protobuf:"fixed32,4,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	MemoryKb        int64                  `protobuf:"varint,5,opt,name=memory_kb,json=memoryKb,proto3" json:"memory_kb,omitempty"`
	Stdout          string                 `protobuf:"bytes,6,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr          string                 `protobuf:"bytes,7,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TestCaseResult) Reset() {
	*x = TestCaseResult{}
	mi := &file_fabric_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCaseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCaseResult) ProtoMessage() {}

func (x *TestCaseResult) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCaseResult.ProtoReflect.Descriptor instead.
func (*TestCaseResult) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{14}
}

func (x *TestCaseResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestCaseResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *TestCaseResult) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *TestCaseResult) GetExecutionTimeMs() float32 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *TestCaseResult) GetMemoryKb() int64 {
	if x != nil {
		return x.MemoryKb
	}
	return 0
}

func (x *TestCaseResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *TestCaseResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

type SubmitResultRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	JobId           string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Verdict         string                 `protobuf:"bytes,3,opt,name=verdict,proto3" json:"verdict,omitempty"`
	RuntimeMs       float32                `protobuf:"fixed32,4,opt,name=runtime_ms,json=runtimeMs,proto3" json:"runtime_ms,omitempty"`
	MemoryKb        int64                  `protobuf:"varint,5,opt,name=memory_kb,json=memoryKb,proto3" json:"memory_kb,omitempty"`
	ExitCode        int32                  `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CompilerOutput  string                 `protobuf:"bytes,8,opt,name=compiler_output,json=compilerOutput,proto3" json:"compiler_output,omitempty"`
	PassedTestcases int32                  `protobuf:"varint,9,opt,name=passed_testcases,json=passedTestcases,proto3" json:"passed_testcases,omitempty"`
	TotalTestcases  int32                  `protobuf:"varint,10,opt,name=total_testcases,json=totalTestcases,proto3" json:"total_testcases,omitempty"`
	TestcaseResults []*TestCaseResult      `protobuf:"bytes,11,rep,name=testcase_results,json=testcaseResults,proto3" json:"testcase_results,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitResultRequest) Reset() {
	*x = SubmitResultRequest{}
	mi := &file_fabric_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResultRequest) ProtoMessage() {}

func (x *SubmitResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResultRequest.ProtoReflect.Descriptor instead.
func (*SubmitResultRequest) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{15}
}

func (x *SubmitResultRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SubmitResultRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitResultRequest) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *SubmitResultRequest) GetRuntimeMs() float32 {
	if x != nil {
		return x.RuntimeMs
	}
	return 0
}

func (x *SubmitResultRequest) GetMemoryKb() int64 {
	if x != nil {
		return x.MemoryKb
	}
	return 0
}

func (x *SubmitResultRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *SubmitResultRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SubmitResultRequest) GetCompilerOutput() string {
	if x != nil {
		return x.CompilerOutput
	}
	return ""
}

func (x *SubmitResultRequest) GetPassedTestcases() int32 {
	if x != nil {
		return x.PassedTestcases
	}
	return 0
}

func (x *SubmitResultRequest) GetTotalTestcases() int32 {
	if x != nil {
		return x.TotalTestcases
	}
	return 0
}

func (x *SubmitResultRequest) GetTestcaseResults() []*TestCaseResult {
	if x != nil {
		return x.TestcaseResults
	}
	return nil
}

type SubmitResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recorded      bool                   `protobuf:"varint,1,opt,name=recorded,proto3" json:"recorded,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResultResponse) Reset() {
	*x = SubmitResultResponse{}
	mi := &file_fabric_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResultResponse) ProtoMessage() {}

func (x *SubmitResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResultResponse.ProtoReflect.Descriptor instead.
func (*SubmitResultResponse) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{16}
}

func (x *SubmitResultResponse) GetRecorded() bool {
	if x != nil {
		return x.Recorded
	}
	return false
}

func (x *SubmitResultResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type NodeTelemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Heartbeat     *HeartbeatRequest      `protobuf:"bytes,3,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeTelemetry) Reset() {
	*x = NodeTelemetry{}
	mi := &file_fabric_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeTelemetry) ProtoMessage() {}

func (x *NodeTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeTelemetry.ProtoReflect.Descriptor instead.
func (*NodeTelemetry) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{17}
}

func (x *NodeTelemetry) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeTelemetry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NodeTelemetry) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

type FabricCommand struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Type          FabricCommand_CommandType `protobuf:"varint,1,opt,name=type,proto3,enum=fabric.v1.FabricCommand_CommandType" json:"type,omitempty"`
	Job           *JobSpec                  `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	Message       string                    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FabricCommand) Reset() {
	*x = FabricCommand{}
	mi := &file_fabric_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FabricCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FabricCommand) ProtoMessage() {}

func (x *FabricCommand) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FabricCommand.ProtoReflect.Descriptor instead.
func (*FabricCommand) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{18}
}

func (x *FabricCommand) GetType() FabricCommand_CommandType {
	if x != nil {
		return x.Type
	}
	return FabricCommand_NOOP
}

func (x *FabricCommand) GetJob() *JobSpec {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *FabricCommand) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_fabric_proto protoreflect.FileDescriptor

const file_fabric_proto_rawDesc = "" +
	"\n" +
	"\ffabric.proto\x12\tfabric.v1\"\xe5\x02\n" +
	"\rHardwareSpecs\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12\x1f\n" +
	"\vcpu_threads\x18\x02 \x01(\x05R\n" +
	"cpuThreads\x12\x1b\n" +
	"\tcpu_model\x18\x03 \x01(\tR\bcpuModel\x12&\n" +
	"\x0ftotal_memory_mb\x18\x04 \x01(\x03R\rtotalMemoryMb\x12.\n" +
	"\x13available_memory_mb\x18\x05 \x01(\x03R\x11availableMemoryMb\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\a \x01(\tR\x04arch\x12%\n" +
	"\x0edocker_version\x18\b \x01(\tR\rdockerVersion\x12%\n" +
	"\x0edocker_healthy\x18\t \x01(\bR\rdockerHealthy\x12/\n" +
	"\x13supported_languages\x18\n" +
	" \x03(\tR\x12supportedLanguages\"\xaa\x01\n" +
	"\x0fDynamicCapacity\x12\x1f\n" +
	"\vjudge_slots\x18\x01 \x01(\x05R\n" +
	"judgeSlots\x12\x1f\n" +
	"\vapi_workers\x18\x02 \x01(\x05R\n" +
	"apiWorkers\x12'\n" +
	"\x0fsse_connections\x18\x03 \x01(\x05R\x0esseConnections\x12,\n" +
	"\x12reserved_memory_mb\x18\x04 \x01(\x03R\x10reservedMemoryMb\"\x88\x02\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12)\n" +
	"\x10enrollment_token\x18\x03 \x01(\tR\x0fenrollmentToken\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x124\n" +
	"\bhardware\x18\x05 \x01(\v2\x18.fabric.v1.HardwareSpecsR\bhardware\x126\n" +
	"\bcapacity\x18\x06 \x01(\v2\x1a.fabric.v1.DynamicCapacityR\bcapacity\"\xef\x01\n" +
	"\x14RegisterNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x03 \x01(\x05R\x18heartbeatIntervalSeconds\x12%\n" +
	"\x0eassigned_queue\x18\x04 \x01(\tR\rassignedQueue\x12'\n" +
	"\x0fmax_concurrency\x18\x05 \x01(\x05R\x0emaxConcurrency\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\xe8\x02\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\"\n" +
	"\rcpu_usage_pct\x18\x02 \x01(\x02R\vcpuUsagePct\x12(\n" +
	"\x10memory_usage_pct\x18\x03 \x01(\x02R\x0ememoryUsagePct\x12.\n" +
	"\x13available_memory_mb\x18\x04 \x01(\x03R\x11availableMemoryMb\x12\x1f\n" +
	"\vactive_jobs\x18\x05 \x01(\x05R\n" +
	"activeJobs\x12,\n" +
	"\x12active_api_workers\x18\x06 \x01(\x05R\x10activeApiWorkers\x12(\n" +
	"\x10active_sse_conns\x18\a \x01(\x05R\x0eactiveSseConns\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\b \x01(\x02R\tlatencyMs\x12%\n" +
	"\x0edocker_healthy\x18\t \x01(\bR\rdockerHealthy\"\x90\x01\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fshould_drain\x18\x03 \x01(\bR\vshouldDrain\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"C\n" +
	"\x10DrainNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"O\n" +
	"\x11DrainNodeResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"+\n" +
	"\x10ReadyNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"O\n" +
	"\x11ReadyNodeResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x84\x01\n" +
	"\x0fClaimJobRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x02R\x0etimeoutSeconds\x12/\n" +
	"\x13supported_languages\x18\x03 \x03(\tR\x12supportedLanguages\"\x89\x01\n" +
	"\bTestCase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05stdin\x18\x02 \x01(\tR\x05stdin\x12'\n" +
	"\x0fexpected_output\x18\x03 \x01(\tR\x0eexpectedOutput\x12\x16\n" +
	"\x06hidden\x18\x04 \x01(\bR\x06hidden\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x02R\x06weight\"\x86\x03\n" +
	"\aJobSpec\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12\x19\n" +
	"\bjob_type\x18\x03 \x01(\tR\ajobType\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\"\n" +
	"\rtime_limit_ms\x18\x06 \x01(\x02R\vtimeLimitMs\x12&\n" +
	"\x0fmemory_limit_mb\x18\a \x01(\x03R\rmemoryLimitMb\x121\n" +
	"\ttestcases\x18\b \x03(\v2\x13.fabric.v1.TestCaseR\ttestcases\x12\x19\n" +
	"\blease_id\x18\t \x01(\tR\aleaseId\x12\x18\n" +
	"\aattempt\x18\n" +
	" \x01(\x05R\aattempt\x12#\n" +
	"\rsubmission_id\x18\v \x01(\tR\fsubmissionId\x12!\n" +
	"\fcontest_slug\x18\f \x01(\tR\vcontestSlug\"Q\n" +
	"\x10ClaimJobResponse\x12\x17\n" +
	"\ahas_job\x18\x01 \x01(\bR\x06hasJob\x12$\n" +
	"\x03job\x18\x02 \x01(\v2\x12.fabric.v1.JobSpecR\x03job\"\xcb\x01\n" +
	"\x0eTestCaseResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\bR\x06passed\x12\x18\n" +
	"\averdict\x18\x03 \x01(\tR\averdict\x12*\n" +
	"\x11execution_time_ms\x18\x04 \x01(\x02R\x0fexecutionTimeMs\x12\x1b\n" +
	"\tmemory_kb\x18\x05 \x01(\x03R\bmemoryKb\x12\x16\n" +
	"\x06stdout\x18\x06 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\a \x01(\tR\x06stderr\"\xa0\x03\n" +
	"\x13SubmitResultRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x18\n" +
	"\averdict\x18\x03 \x01(\tR\averdict\x12\x1d\n" +
	"\n" +
	"runtime_ms\x18\x04 \x01(\x02R\truntimeMs\x12\x1b\n" +
	"\tmemory_kb\x18\x05 \x01(\x03R\bmemoryKb\x12\x1b\n" +
	"\texit_code\x18\x06 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12'\n" +
	"\x0fcompiler_output\x18\b \x01(\tR\x0ecompilerOutput\x12)\n" +
	"\x10passed_testcases\x18\t \x01(\x05R\x0fpassedTestcases\x12'\n" +
	"\x0ftotal_testcases\x18\n" +
	" \x01(\x05R\x0etotalTestcases\x12D\n" +
	"\x10testcase_results\x18\v \x03(\v2\x19.fabric.v1.TestCaseResultR\x0ftestcaseResults\"J\n" +
	"\x14SubmitResultResponse\x12\x1a\n" +
	"\brecorded\x18\x01 \x01(\bR\brecorded\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x81\x01\n" +
	"\rNodeTelemetry\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x129\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1b.fabric.v1.HeartbeatRequestR\theartbeat\"\xd0\x01\n" +
	"\rFabricCommand\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.fabric.v1.FabricCommand.CommandTypeR\x04type\x12$\n" +
	"\x03job\x18\x02 \x01(\v2\x12.fabric.v1.JobSpecR\x03job\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"E\n" +
	"\vCommandType\x12\b\n" +
	"\x04NOOP\x10\x00\x12\x10\n" +
	"\fDISPATCH_JOB\x10\x01\x12\t\n" +
	"\x05DRAIN\x10\x02\x12\x0f\n" +
	"\vRECONFIGURE\x10\x032\xa0\x04\n" +
	"\x12FabricControlPlane\x12O\n" +
	"\fRegisterNode\x12\x1e.fabric.v1.RegisterNodeRequest\x1a\x1f.fabric.v1.RegisterNodeResponse\x12J\n" +
	"\rSendHeartbeat\x12\x1b.fabric.v1.HeartbeatRequest\x1a\x1c.fabric.v1.HeartbeatResponse\x12F\n" +
	"\tDrainNode\x12\x1b.fabric.v1.DrainNodeRequest\x1a\x1c.fabric.v1.DrainNodeResponse\x12F\n" +
	"\tMarkReady\x12\x1b.fabric.v1.ReadyNodeRequest\x1a\x1c.fabric.v1.ReadyNodeResponse\x12C\n" +
	"\bClaimJob\x12\x1a.fabric.v1.ClaimJobRequest\x1a\x1b.fabric.v1.ClaimJobResponse\x12O\n" +
	"\fSubmitResult\x12\x1e.fabric.v1.SubmitResultRequest\x1a\x1f.fabric.v1.SubmitResultResponse\x12G\n" +
	"\rConnectFabric\x12\x18.fabric.v1.NodeTelemetry\x1a\x18.fabric.v1.FabricCommand(\x010\x01B0Z.chaoscomputerclub.in/node-agent/internal/pb;pbb\x06proto3"

var (
	file_fabric_proto_rawDescOnce sync.Once
	file_fabric_proto_rawDescData []byte
)

func file_fabric_proto_rawDescGZIP() []byte {
	file_fabric_proto_rawDescOnce.Do(func() {
		file_fabric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fabric_proto_rawDesc), len(file_fabric_proto_rawDesc)))
	})
	return file_fabric_proto_rawDescData
}

var file_fabric_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fabric_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_fabric_proto_goTypes = []any{
	(FabricCommand_CommandType)(0), // 0: fabric.v1.FabricCommand.CommandType
	(*HardwareSpecs)(nil),          // 1: fabric.v1.HardwareSpecs
	(*DynamicCapacity)(nil),        // 2: fabric.v1.DynamicCapacity
	(*RegisterNodeRequest)(nil),    // 3: fabric.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),   // 4: fabric.v1.RegisterNodeResponse
	(*HeartbeatRequest)(nil),       // 5: fabric.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 6: fabric.v1.HeartbeatResponse
	(*DrainNodeRequest)(nil),       // 7: fabric.v1.DrainNodeRequest
	(*DrainNodeResponse)(nil),      // 8: fabric.v1.DrainNodeResponse
	(*ReadyNodeRequest)(nil),       // 9: fabric.v1.ReadyNodeRequest
	(*ReadyNodeResponse)(nil),      // 10: fabric.v1.ReadyNodeResponse
	(*ClaimJobRequest)(nil),        // 11: fabric.v1.ClaimJobRequest
	(*TestCase)(nil),               // 12: fabric.v1.TestCase
	(*JobSpec)(nil),                // 13: fabric.v1.JobSpec
	(*ClaimJobResponse)(nil),       // 14: fabric.v1.ClaimJobResponse
	(*TestCaseResult)(nil),         // 15: fabric.v1.TestCaseResult
	(*SubmitResultRequest)(nil),    // 16: fabric.v1.SubmitResultRequest
	(*SubmitResultResponse)(nil),   // 17: fabric.v1.SubmitResultResponse
	(*NodeTelemetry)(nil),          // 18: fabric.v1.NodeTelemetry
	(*FabricCommand)(nil),          // 19: fabric.v1.FabricCommand
}
var file_fabric_proto_depIdxs = []int32{
	1,  // 0: fabric.v1.RegisterNodeRequest.hardware:type_name -> fabric.v1.HardwareSpecs
	2,  // 1: fabric.v1.RegisterNodeRequest.capacity:type_name -> fabric.v1.DynamicCapacity
	12, // 2: fabric.v1.JobSpec.testcases:type_name -> fabric.v1.TestCase
	13, // 3: fabric.v1.ClaimJobResponse.job:type_name -> fabric.v1.JobSpec
	15, // 4: fabric.v1.SubmitResultRequest.testcase_results:type_name -> fabric.v1.TestCaseResult
	5,  // 5: fabric.v1.NodeTelemetry.heartbeat:type_name -> fabric.v1.HeartbeatRequest
	0,  // 6: fabric.v1.FabricCommand.type:type_name -> fabric.v1.FabricCommand.CommandType
	13, // 7: fabric.v1.FabricCommand.job:type_name -> fabric.v1.JobSpec
	3,  // 8: fabric.v1.FabricControlPlane.RegisterNode:input_type -> fabric.v1.RegisterNodeRequest
	5,  // 9: fabric.v1.FabricControlPlane.SendHeartbeat:input_type -> fabric.v1.HeartbeatRequest
	7,  // 10: fabric.v1.FabricControlPlane.DrainNode:input_type -> fabric.v1.DrainNodeRequest
	9,  // 11: fabric.v1.FabricControlPlane.MarkReady:input_type -> fabric.v1.ReadyNodeRequest
	11, // 12: fabric.v1.FabricControlPlane.ClaimJob:input_type -> fabric.v1.ClaimJobRequest
	16, // 13: fabric.v1.FabricControlPlane.SubmitResult:input_type -> fabric.v1.SubmitResultRequest
	18, // 14: fabric.v1.FabricControlPlane.ConnectFabric:input_type -> fabric.v1.NodeTelemetry
	4,  // 15: fabric.v1.FabricControlPlane.RegisterNode:output_type -> fabric.v1.RegisterNodeResponse
	6,  // 16: fabric.v1.FabricControlPlane.SendHeartbeat:output_type -> fabric.v1.HeartbeatResponse
	8,  // 17: fabric.v1.FabricControlPlane.DrainNode:output_type -> fabric.v1.DrainNodeResponse
	10, // 18: fabric.v1.FabricControlPlane.MarkReady:output_type -> fabric.v1.ReadyNodeResponse
	14, // 19: fabric.v1.FabricControlPlane.ClaimJob:output_type -> fabric.v1.ClaimJobResponse
	17, // 20: fabric.v1.FabricControlPlane.SubmitResult:output_type -> fabric.v1.SubmitResultResponse
	19, // 21: fabric.v1.FabricControlPlane.ConnectFabric:output_type -> fabric.v1.FabricCommand
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_fabric_proto_init() }
func file_fabric_proto_init() {
	if File_fabric_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fabric_proto_rawDesc), len(file_fabric_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fabric_proto_goTypes,
		DependencyIndexes: file_fabric_proto_depIdxs,
		EnumInfos:         file_fabric_proto_enumTypes,
		MessageInfos:      file_fabric_proto_msgTypes,
	}.Build()
	File_fabric_proto = out.File
	file_fabric_proto_goTypes = nil
	file_fabric_proto_depIdxs = nil
}
