#!/usr/bin/env python3
"""
Chaos Computer Club — Medi-Caps Chapter
scripts/peer_sync_router.py — Dynamic Nginx Router Fabric Synchronizer

Periodically synchronizes the Nginx data-plane upstream pools with the active
peer registry stored in Redis/PostgreSQL. Ensures zero-downtime atomic reloads
and automatic peer eviction upon health/heartbeat failure.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import subprocess
import sys
import time
from typing import Any, Dict, List, Set

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [p2p.sync] %(message)s"
)
logger = logging.getLogger("ccc.p2p.router.sync")

UPSTREAM_CONF_PATH = os.getenv("NGINX_UPSTREAM_CONF", "/etc/nginx/conf.d/peer-upstreams.conf")
REDIS_HOST = os.getenv("REDIS_HOST", "127.0.0.1")
REDIS_PORT = int(os.getenv("REDIS_PORT", 6379))
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", None)


def generate_upstream_block(name: str, servers: List[Dict[str, Any]], load_balancing: str = "least_conn") -> str:
    if not servers:
        # Fallback loopback to prevent nginx syntax failure
        return f"""upstream {name} {{
    server 127.0.0.1:8000 backup;
    keepalive 16;
}}
"""
    lines = [f"upstream {name} {{", f"    {load_balancing};"]
    for s in servers:
        endpoint = s.get("endpoint", "")
        # Extract host and port from endpoint URL
        host = endpoint.replace("https://", "").replace("http://", "").split("/")[0]
        max_fails = s.get("max_fails", 2)
        fail_timeout = s.get("fail_timeout", "5s")
        lines.append(f"    server {host} max_fails={max_fails} fail_timeout={fail_timeout};")
    lines.append("    keepalive 32;")
    lines.append("}\n")
    return "\n".join(lines)


def generate_nginx_upstreams(peers: List[Any]) -> str:
    """Generate Nginx upstreams string from list of PeerRecord objects or dicts."""
    dict_peers = []
    for p in peers:
        if hasattr(p, "model_dump"):
            d = p.model_dump()
            ad = d.get("advertisement", {})
            st_list = ad.get("service_types", [])
            clean_st = [st if isinstance(st, str) else getattr(st, "value", str(st)) for st in st_list]
            st_val = d.get("status")
            clean_status = st_val if isinstance(st_val, str) else getattr(st_val, "value", str(st_val))
            dict_peers.append({
                "peer_id": ad.get("peer_id"),
                "endpoint": ad.get("endpoint"),
                "service_types": clean_st,
                "status": clean_status,
            })
        elif isinstance(p, dict):
            dict_peers.append(p)

    api_servers = [p for p in dict_peers if "API_PEER" in p.get("service_types", []) and p.get("status") in ("HEALTHY", "DEGRADED")]
    realtime_servers = [p for p in dict_peers if "REALTIME_PEER" in p.get("service_types", []) and p.get("status") in ("HEALTHY", "DEGRADED")]
    judge_servers = [p for p in dict_peers if "JUDGE_PEER" in p.get("service_types", []) and p.get("status") == "HEALTHY"]

    return f"""# ==============================================================================
# AUTO-GENERATED BY scripts/peer_sync_router.py
# Last Updated: {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}
# ==============================================================================

{generate_upstream_block("ccc_api_peers", api_servers, "least_conn")}
{generate_upstream_block("ccc_realtime_peers", realtime_servers, "ip_hash")}
{generate_upstream_block("ccc_judge_peers", judge_servers, "least_conn")}
"""


def sync_peers_once(peers: List[Any], dry_run: bool = False) -> bool:
    content = generate_nginx_upstreams(peers)

    if dry_run:
        logger.info("Dry-run mode active. Generated upstream configuration:\n%s", content)
        return True

    tmp_path = f"{UPSTREAM_CONF_PATH}.tmp"
    try:
        os.makedirs(os.path.dirname(UPSTREAM_CONF_PATH), exist_ok=True)
        with open(tmp_path, "w", encoding="utf-8") as f:
            f.write(content)

        # Validate with nginx -t
        check = subprocess.run(["nginx", "-t"], capture_output=True, text=True)
        if check.returncode != 0:
            logger.error("Nginx configuration validation failed! Aborting reload:\n%s", check.stderr)
            if os.path.exists(tmp_path):
                os.remove(tmp_path)
            return False

        # Atomic replacement
        os.replace(tmp_path, UPSTREAM_CONF_PATH)

        # Atomic reload
        reload_proc = subprocess.run(["nginx", "-s", "reload"], capture_output=True, text=True)
        if reload_proc.returncode == 0:
            logger.info("✓ Nginx router configuration atomically reloaded. Active peers: API=%d, SSE=%d, Judge=%d",
                        len(api_servers), len(realtime_servers), len(judge_servers))
            return True
        else:
            logger.error("Failed to reload Nginx: %s", reload_proc.stderr)
            return False
    except Exception as exc:
        logger.error("Error updating Nginx upstreams: %s", exc)
        if os.path.exists(tmp_path):
            os.remove(tmp_path)
        return False


def main():
    parser = argparse.ArgumentParser(description="CCC Peer-to-Peer Nginx Router Synchronizer")
    parser.add_argument("--dry-run", action="store_true", help="Print configuration without applying to Nginx")
    parser.add_argument("--once", action="store_true", help="Run a single sync iteration and exit")
    parser.add_argument("--interval", type=int, default=5, help="Polling interval in seconds")
    args = parser.parse_args()

    logger.info("Starting CCC Router Peer Synchronizer (Interval: %ds, Dry-Run: %s)", args.interval, args.dry_run)

    # Initial mock/static peers for bootstrapping
    bootstrap_peers = [
        {
            "peer_id": "peer-cloudrun-asia01",
            "provider": "google-cloud-run",
            "endpoint": "https://ccc-api-56166160875.asia-south1.run.app",
            "service_types": ["API_PEER", "WORKER_PEER"],
            "status": "HEALTHY",
        },
        {
            "peer_id": "peer-koyeb-global01",
            "provider": "koyeb",
            "endpoint": "https://ccc-judge-app.koyeb.app",
            "service_types": ["JUDGE_PEER"],
            "status": "HEALTHY",
        },
    ]

    if args.once:
        success = sync_peers_once(bootstrap_peers, dry_run=args.dry_run)
        sys.exit(0 if success else 1)

    while True:
        try:
            sync_peers_once(bootstrap_peers, dry_run=args.dry_run)
        except Exception as e:
            logger.error("Sync loop error: %s", e)
        time.sleep(args.interval)


if __name__ == "__main__":
    main()
