/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalLeaderboardRouteImport } from './routes/portal.leaderboard'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalVerifyRouteImport } from './routes/portal.verify'
import { Route as PortalContestsIndexRouteImport } from './routes/portal.contests.index'
import { Route as PortalContestsContestSlugRouteImport } from './routes/portal.contests.$contestSlug'
import { Route as PortalProblemsIndexRouteImport } from './routes/portal.problems.index'
import { Route as PortalProblemsProblemSlugRouteImport } from './routes/portal.problems.$problemSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLeaderboardRoute = PortalLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalVerifyRoute = PortalVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContestsIndexRoute = PortalContestsIndexRouteImport.update({
  id: '/contests/',
  path: '/contests/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContestsContestSlugRoute =
  PortalContestsContestSlugRouteImport.update({
    id: '/contests/$contestSlug',
    path: '/contests/$contestSlug',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalProblemsIndexRoute = PortalProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProblemsProblemSlugRoute =
  PortalProblemsProblemSlugRouteImport.update({
    id: '/problems/$problemSlug',
    path: '/problems/$problemSlug',
    getParentRoute: () => PortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/portal/leaderboard': typeof PortalLeaderboardRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/verify': typeof PortalVerifyRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/contests/$contestSlug': typeof PortalContestsContestSlugRoute
  '/portal/problems/$problemSlug': typeof PortalProblemsProblemSlugRoute
  '/portal/contests/': typeof PortalContestsIndexRoute
  '/portal/problems/': typeof PortalProblemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/portal/leaderboard': typeof PortalLeaderboardRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/verify': typeof PortalVerifyRoute
  '/portal': typeof PortalIndexRoute
  '/portal/contests/$contestSlug': typeof PortalContestsContestSlugRoute
  '/portal/problems/$problemSlug': typeof PortalProblemsProblemSlugRoute
  '/portal/contests': typeof PortalContestsIndexRoute
  '/portal/problems': typeof PortalProblemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/portal/leaderboard': typeof PortalLeaderboardRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/verify': typeof PortalVerifyRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/contests/$contestSlug': typeof PortalContestsContestSlugRoute
  '/portal/problems/$problemSlug': typeof PortalProblemsProblemSlugRoute
  '/portal/contests/': typeof PortalContestsIndexRoute
  '/portal/problems/': typeof PortalProblemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/portal'
    | '/recover'
    | '/signup'
    | '/portal/leaderboard'
    | '/portal/profile'
    | '/portal/verify'
    | '/portal/'
    | '/portal/contests/$contestSlug'
    | '/portal/problems/$problemSlug'
    | '/portal/contests/'
    | '/portal/problems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/recover'
    | '/signup'
    | '/portal/leaderboard'
    | '/portal/profile'
    | '/portal/verify'
    | '/portal'
    | '/portal/contests/$contestSlug'
    | '/portal/problems/$problemSlug'
    | '/portal/contests'
    | '/portal/problems'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/login'
    | '/portal'
    | '/recover'
    | '/signup'
    | '/portal/leaderboard'
    | '/portal/profile'
    | '/portal/verify'
    | '/portal/'
    | '/portal/contests/$contestSlug'
    | '/portal/problems/$problemSlug'
    | '/portal/contests/'
    | '/portal/problems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  RecoverRoute: typeof RecoverRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/leaderboard': {
      id: '/portal/leaderboard'
      path: '/leaderboard'
      fullPath: '/portal/leaderboard'
      preLoaderRoute: typeof PortalLeaderboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/verify': {
      id: '/portal/verify'
      path: '/verify'
      fullPath: '/portal/verify'
      preLoaderRoute: typeof PortalVerifyRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/contests/': {
      id: '/portal/contests/'
      path: '/contests'
      fullPath: '/portal/contests/'
      preLoaderRoute: typeof PortalContestsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/contests/$contestSlug': {
      id: '/portal/contests/$contestSlug'
      path: '/contests/$contestSlug'
      fullPath: '/portal/contests/$contestSlug'
      preLoaderRoute: typeof PortalContestsContestSlugRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/problems/': {
      id: '/portal/problems/'
      path: '/problems'
      fullPath: '/portal/problems/'
      preLoaderRoute: typeof PortalProblemsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/problems/$problemSlug': {
      id: '/portal/problems/$problemSlug'
      path: '/problems/$problemSlug'
      fullPath: '/portal/problems/$problemSlug'
      preLoaderRoute: typeof PortalProblemsProblemSlugRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalLeaderboardRoute: typeof PortalLeaderboardRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalVerifyRoute: typeof PortalVerifyRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalContestsContestSlugRoute: typeof PortalContestsContestSlugRoute
  PortalProblemsProblemSlugRoute: typeof PortalProblemsProblemSlugRoute
  PortalContestsIndexRoute: typeof PortalContestsIndexRoute
  PortalProblemsIndexRoute: typeof PortalProblemsIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalLeaderboardRoute: PortalLeaderboardRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalVerifyRoute: PortalVerifyRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalContestsContestSlugRoute: PortalContestsContestSlugRoute,
  PortalProblemsProblemSlugRoute: PortalProblemsProblemSlugRoute,
  PortalContestsIndexRoute: PortalContestsIndexRoute,
  PortalProblemsIndexRoute: PortalProblemsIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  RecoverRoute: RecoverRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
