/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalLeaderboardRouteImport } from './routes/portal/leaderboard'
import { Route as PortalProfileRouteImport } from './routes/portal/profile'
import { Route as PortalContestsIndexRouteImport } from './routes/portal/contests/index'
import { Route as PortalContestsContestSlugRouteImport } from './routes/portal/contests/$contestSlug'
import { Route as PortalEventsIndexRouteImport } from './routes/portal/events/index'
import { Route as PortalEventsEventSlugRouteImport } from './routes/portal/events/$eventSlug'
import { Route as PortalProblemsIndexRouteImport } from './routes/portal/problems/index'
import { Route as PortalProblemsProblemSlugRouteImport } from './routes/portal/problems/$problemSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalLeaderboardRoute = PortalLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalContestsIndexRoute = PortalContestsIndexRouteImport.update({
  id: '/contests/',
  path: '/contests/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalContestsContestSlugRoute =
  PortalContestsContestSlugRouteImport.update({
    id: '/contests/$contestSlug',
    path: '/contests/$contestSlug',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalEventsIndexRoute = PortalEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalEventsEventSlugRoute = PortalEventsEventSlugRouteImport.update({
  id: '/events/$eventSlug',
  path: '/events/$eventSlug',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalProblemsIndexRoute = PortalProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalProblemsProblemSlugRoute =
  PortalProblemsProblemSlugRouteImport.update({
    id: '/problems/$problemSlug',
    path: '/problems/$problemSlug',
    getParentRoute: () => PortalRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/portal/leaderboard': typeof PortalLeaderboardRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/contests/$contestSlug': typeof PortalContestsContestSlugRoute
  '/portal/events/$eventSlug': typeof PortalEventsEventSlugRoute
  '/portal/problems/$problemSlug': typeof PortalProblemsProblemSlugRoute
  '/portal/contests/': typeof PortalContestsIndexRoute
  '/portal/events/': typeof PortalEventsIndexRoute
  '/portal/problems/': typeof PortalProblemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/portal/leaderboard': typeof PortalLeaderboardRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal': typeof PortalIndexRoute
  '/portal/contests/$contestSlug': typeof PortalContestsContestSlugRoute
  '/portal/events/$eventSlug': typeof PortalEventsEventSlugRoute
  '/portal/problems/$problemSlug': typeof PortalProblemsProblemSlugRoute
  '/portal/contests': typeof PortalContestsIndexRoute
  '/portal/events': typeof PortalEventsIndexRoute
  '/portal/problems': typeof PortalProblemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/portal/leaderboard': typeof PortalLeaderboardRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/contests/$contestSlug': typeof PortalContestsContestSlugRoute
  '/portal/events/$eventSlug': typeof PortalEventsEventSlugRoute
  '/portal/problems/$problemSlug': typeof PortalProblemsProblemSlugRoute
  '/portal/contests/': typeof PortalContestsIndexRoute
  '/portal/events/': typeof PortalEventsIndexRoute
  '/portal/problems/': typeof PortalProblemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/login'
    | '/recover'
    | '/signup'
    | '/portal/leaderboard'
    | '/portal/profile'
    | '/portal/'
    | '/portal/contests/$contestSlug'
    | '/portal/events/$eventSlug'
    | '/portal/problems/$problemSlug'
    | '/portal/contests/'
    | '/portal/events/'
    | '/portal/problems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover'
    | '/signup'
    | '/portal/leaderboard'
    | '/portal/profile'
    | '/portal'
    | '/portal/contests/$contestSlug'
    | '/portal/events/$eventSlug'
    | '/portal/problems/$problemSlug'
    | '/portal/contests'
    | '/portal/events'
    | '/portal/problems'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/login'
    | '/recover'
    | '/signup'
    | '/portal/leaderboard'
    | '/portal/profile'
    | '/portal/'
    | '/portal/contests/$contestSlug'
    | '/portal/events/$eventSlug'
    | '/portal/problems/$problemSlug'
    | '/portal/contests/'
    | '/portal/events/'
    | '/portal/problems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverRoute: typeof RecoverRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/leaderboard': {
      id: '/portal/leaderboard'
      path: '/leaderboard'
      fullPath: '/portal/leaderboard'
      preLoaderRoute: typeof PortalLeaderboardRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/contests/': {
      id: '/portal/contests/'
      path: '/contests'
      fullPath: '/portal/contests/'
      preLoaderRoute: typeof PortalContestsIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/contests/$contestSlug': {
      id: '/portal/contests/$contestSlug'
      path: '/contests/$contestSlug'
      fullPath: '/portal/contests/$contestSlug'
      preLoaderRoute: typeof PortalContestsContestSlugRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/events/': {
      id: '/portal/events/'
      path: '/events'
      fullPath: '/portal/events/'
      preLoaderRoute: typeof PortalEventsIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/events/$eventSlug': {
      id: '/portal/events/$eventSlug'
      path: '/events/$eventSlug'
      fullPath: '/portal/events/$eventSlug'
      preLoaderRoute: typeof PortalEventsEventSlugRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/problems/': {
      id: '/portal/problems/'
      path: '/problems'
      fullPath: '/portal/problems/'
      preLoaderRoute: typeof PortalProblemsIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/problems/$problemSlug': {
      id: '/portal/problems/$problemSlug'
      path: '/problems/$problemSlug'
      fullPath: '/portal/problems/$problemSlug'
      preLoaderRoute: typeof PortalProblemsProblemSlugRouteImport
      parentRoute: typeof PortalRouteRoute
    }
  }
}

interface PortalRouteRouteChildren {
  PortalLeaderboardRoute: typeof PortalLeaderboardRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalContestsContestSlugRoute: typeof PortalContestsContestSlugRoute
  PortalEventsEventSlugRoute: typeof PortalEventsEventSlugRoute
  PortalProblemsProblemSlugRoute: typeof PortalProblemsProblemSlugRoute
  PortalContestsIndexRoute: typeof PortalContestsIndexRoute
  PortalEventsIndexRoute: typeof PortalEventsIndexRoute
  PortalProblemsIndexRoute: typeof PortalProblemsIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalLeaderboardRoute: PortalLeaderboardRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalContestsContestSlugRoute: PortalContestsContestSlugRoute,
  PortalEventsEventSlugRoute: PortalEventsEventSlugRoute,
  PortalProblemsProblemSlugRoute: PortalProblemsProblemSlugRoute,
  PortalContestsIndexRoute: PortalContestsIndexRoute,
  PortalEventsIndexRoute: PortalEventsIndexRoute,
  PortalProblemsIndexRoute: PortalProblemsIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverRoute: RecoverRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
