export {
  AlertDialog,
  AlertDialogTrigger,
  AlertDialogPopup,
  AlertDialogContent,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogPortal,
  AlertDialogBackdrop,
  AlertDialogOverlay,
  AlertDialogClose,
  AlertDialogAction,
  AlertDialogCancel,
  BaseAlertDialogDemo,
  useAlertDialog,
  type AlertDialogFlipDirection,
  type AlertDialogProps,
  type AlertDialogPopupProps,
  type AlertDialogBackdropProps,
} from "@/components/animate-ui/primitives/base/alert-dialog";
